---
- hosts: webservers
  become: True
  tasks:
    - name: start the container
      docker_container:
        name: dockerintegration:1.0
        image: maheesh123/dockerintegration:1.0
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
        
